apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react
  namespace: react

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grad.arieldevops.tech
  rules:
  - host: grad.arieldevops.tech
    http:
      paths:
      - path: /react
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
