apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 199051453468.dkr.ecr.eu-central-1.amazonaws.com/backend-eden:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/example
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: db-57xsl
        ports:
        - containerPort: 8080
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']