name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to JFrog Artifactory
      run: echo ${{ secrets.JF_ACCESS_TOKEN }} | docker login ${{ secrets.JF_URL }} -u

    - name: Build and push
      run: |
        docker-compose -f ./docker-compose.yml build
        docker tag mysql:8.0.27 nx1x.jfrog.io/nx1x-docker-local/mysql:github-actions-1
        docker push nx1x.jfrog.io/nx1x-docker-local/mysql:github-actions-1
        docker tag react-java0mysql-backend nx1x.jfrog.io/nx1x-docker-local/react-java0mysql-backend:github-actions-1
        docker push nx1x.jfrog.io/nx1x-docker-local/react-java0mysql-backend:github-actions-1
        docker tag react-java0mysql-frontend nx1x.jfrog.io/nx1x-docker-local/react-java0mysql-frontend:github-actions-1
        docker push nx1x.jfrog.io/nx1x-docker-local/react-java0mysql-frontend:github-actions-1

    - name: Test containers
      run: |
        docker-compose up -d
        # Add your test commands here
