name: Module-6-docker-compose

on:
  push:
    branches: [ "Dev"]
  pull_request:
    branches: [ "Dev"]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose
      run: sudo docker compose up -d
      
  Test:
    needs: build 
    runs-on: self-hosted
    steps:
      - name: list containers
        run: |
          sleep 15 && sudo docker ps -a |grep "Exited"
          # if one container has exited the exit_status would be 0
          exit_status=$?
          if [ $exit_status -eq 1 ]; then
            echo "list Test passed"
          else
            echo "List Test Failed."
          fi
      - name: test front end container  
        run: sleep 5 && curl -s http://localhost:3000
 
   


