name: Module-6-docker-compose

on:
  push:
    branches: [ "Dev"]
  pull_request:
    branches: [ "Dev"]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose
      run: sudo docker compose up -d
      
  Test:
    needs: build 
    runs-on: self-hosted
    steps:
      - name: list containers
        run: |
         sleep 15 
         if [ $(sudo docker ps -a | grep -q "Exited") ]; then
            echo "At least one container in 'Exited' state found. List Test Failed."
         else
            echo "No containers in 'Exited' state found. List Test passed."
         fi
      - name: test front end container  
        run: sleep 5 && curl -s http://localhost:3000
  push_to_dockerHub:
    needs: build
    runs-on: self-hosted
    steps:
      - name: docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: | 
          echo "${DOCKERHUB_TOKEN}" | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
          
          sudo docker images 
          
        
     
 
   


