name: Module-6-docker-compose

on:
  push:
    branches: [ "Dev"]
  pull_request:
    branches: [ "Dev"]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose
      run: sudo docker compose up -d
      
  Test:
    needs: build 
    runs-on: self-hosted
    steps:
      - name: list containers
        run: |
          # List containers and filter for "Exited" containers
          docker ps -a | grep -q "Exited"

          # Capture the exit status of the previous command
          exit_status=$?

          if [ $exit_status -eq 0 ]; then
            echo "At least one container in 'Exited' state found. List Test Failed."
          else
            echo "No containers in 'Exited' state found. List Test passed."
          fi
      - name: test front end container  
        run: sleep 5 && curl -s http://localhost:3000
 
   


