name: Module-6-docker-compose

on:
  push:
    branches: [ "Dev"]
  pull_request:
    branches: [ "Dev"]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose
      run: sudo docker compose up -d
      
  Test:
    needs: build 
    runs-on: self-hosted
    steps:
      - name: list containers
        run: |
          sleep 15
         
          exited_containers=$(sudo docker ps -a | grep "Exited")
          if [ $exit_containers -eq 1 ]; then
            echo "list Test passed"
            exit 0
          else
            echo "List Test Failed."
            exit 1
          fi
      - name: test front end container  
        run: sleep 5 && curl -s http://localhost:3000
 
   


