name: Module-6-docker-compose

on:
  push:
    branches: [ "Dev"]
  pull_request:
    branches: [ "Dev"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose
      run: docker compose up -d
      env:
          NETWORK_MODE: react-java0mysql_app-network
    - name: list containers
      run: sleep 15 && docker ps -a
    - name: test front end container  
      run: sleep 5 && curl http://loclhost:3000
    - name: check logs
      run: docker logs react-java0mysql-backend-1 && docker inspect react-java0mysql-backend-1
   


